
@startuml
left to right direction
 actor Cliente as g

 usecase (Cancelar Pedido)
 usecase (Confirmar Pedido)

g --(Confirmar Pedido)
g --(Cancelar Pedido)
(Devolver cambio)

(Cancelar Pedido)..(Devolver cambio): include
(Confirmar Pedido)..(Devolver cambio):include
@enduml


