
@startuml
:usuario:
:Administrador:

(Iniciar sesion)
(Recuperar contraseña)
(Modificar contraseña)
(Cerrar sesion)
(Registrar usuario)
(Instalar programa)

usuario -- (Iniciar sesion)
usuario -- (Recuperar contraseña)
usuario -- (Cerrar sesion)
usuario -- (Modificar contraseña)

Administrador --|> usuario

Administrador -- (Registrar usuario)
Administrador - (Instalar programa)

@enduml


